const START_LAT = 35.68950;
const START_LNG = 139.69235;
const START_ZOOM = 12;
const MARKER_WIDTH = 40;
const MAIN_MARKER_WIDTH = 52;

const MIN_LENGTH_TITLE = 30;
const MAX_LENGTH_TITLE = 100;
const MAX_PRICE = 100000;

export {
  START_LAT,
  START_LNG,
  START_ZOOM,
  MARKER_WIDTH,
  MAIN_MARKER_WIDTH,
  MIN_LENGTH_TITLE,
  MAX_LENGTH_TITLE,
  MAX_PRICE,
};
